### ISSUE TITLE
Create an additional validation for public IP address requirement

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#192]
This covers augmenting `quads-cli --define-cloud` with an optional argparse value like `--extnet true` (default being false) that should create a stub file (via subprocess or similar) that holds up release of an assignment until a public VLAN can be deployed on the 4th interface of the hosts.

This will then correspond to a validation check that will gate release if the stub file is present.

This should land somewhere around here in the validations:

https://github.com/redhat-performance/quads/blob/master/bin/quads-validate-env.sh#L158

The subsequent notification email for failing this test should contain verbage that there's a requirement for additional public VLAN in which operator action hasn't been taken.

**Why are we doing this?**

* We need a way to roll out public VLANs along with assignments that need them at the same time
* We intend to fully automate this in `1.1` but need something now
* This should be a minimally invasive change.

**Comment by sadsfae** [comment]
```
---
pubnet01:
  - id: 1
  - vlanid: 601
  - iprange: 10.12.80.0/23
  - netmask: 255.255.254.0
  - gateway: 10.12.81.254
  - ipfree: 510
  - owner: abond
  - ticket: 435354
  - cloud: 20
pubnet02:
  - id: 2
  - vlanid: 602
  - iprange: 10.12.82.0/23
  - netmask: 255.255.254.0
  - gateway: 10.12.83.254
  - ipfree: 510
  - owner: abond
  - ticket: 434354
  - cloud: 16
```
