### ISSUE TITLE
Preserve History for Machine Assignments

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#58]
We should be preserving cloud definitions in the data stored on disk similar to the host history information. For example, as allocations are used, and expire, and later for a new project the cloud environment is redefined.  This can be implemented under a ```cloud_history``` attribute that looks something like this:

```
cloud_history:
  cloud01:
    0:
      ccusers: []
      description: Pool of available servers
      owner: nobody
      qinq: '0'
      ticket: '000000'
[...]
  cloud07:
    0:
      ccusers: []
      description: AMQ OpenStack
      owner: jsmith
      qinq: '0'
      ticket: '429833'
    1492047523:
      ccusers: []
      description: AMQ OpenStack
      owner: mwagner
      qinq: '0'
      ticket: '429833'
```

Then when you query for the summary (or full summary), when using the ```--date``` string with a date/time in the past you will correctly see the previously defined name of the environment.

e.g.

```
$ ./bin/quads.py --full-summary --date "2017-04-12 21:00"
cloud01 : 36 (Pool of available servers)
cloud02 : 10 (OSP Metrics/Memory Calc)
cloud03 : 15 (Gluster RHGS FIO)
cloud04 : 0 (OSP and NW roles)
cloud05 : 37 (Satellite)
cloud06 : 0 (OSP RHCS)
cloud07 : 28 (AMQ OpenStack)
cloud08 : 0 (OSP10 Testing)
cloud09 : 0 (RHCS2.0/HCI)
cloud10 : 0 (Openshift + OSPD testing)
cloud11 : 0 (OSP BZs)
cloud12 : 12 (OSP10 + HCI + RHCS)
cloud13 : 0 (JBoss EAP)
cloud14 : 13 (ODL OSP)
cloud15 : 0 (OSP storage)
cloud16 : 36 (OSP11 Ocata)

$ ./bin/quads.py --full-summary
cloud01 : 36 (Pool of available servers)
cloud02 : 10 (OSP Metrics/Memory Calc)
cloud03 : 15 (Gluster RHGS FIO)
cloud04 : 0 (OSP and NW roles)
cloud05 : 37 (Satellite)
cloud06 : 0 (OSP RHCS)
cloud07 : 28 (Another Random allocation)
cloud08 : 0 (OSP10 Testing)
cloud09 : 0 (RHCS2.0/HCI)
cloud10 : 0 (Openshift + OSPD testing)
cloud11 : 0 (OSP BZs)
cloud12 : 12 (OSP10 + HCI + RHCS)
cloud13 : 0 (Random allocation)
cloud14 : 13 (ODL OSP)
cloud15 : 0 (OSP storage)
cloud16 : 36 (OSP11 Ocata)
```

Notice that cloud07 and cloud13 were redefined in the test data
yet looking backward, we can see the previously assigned name.
