### ISSUE TITLE
[BUG] quads --ls-filter doesn't properly account for disks.count

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#586]
I'd expect this query to only return Dell R640's with only a single disk, instead it returns all systems.

```
# quads --ls-hosts --filter "model==r640, disks.count==1" | wc -l
347
```

Same results with `disks.count>=1`

```
# quads --ls-hosts --filter "model==r640, disks.count<=1" | wc -l
347
```

**Comment by kambiz-aghaiepour** [comment]
I think the issue with the way the query is constructed is that it will match hosts that have only 1 disk of ANY type.  For example:

```
# quads --host somehost.example.com --ls-disks
disk0:
  type: scsi
  size: 480
  count: 1
disk1:
  type: scsi
  size: 1920
  count: 2
disk2:
  type: nvme
  size: 1600
  count: 1
```

The above host has a total of 4 disks, but it only has a 1 count for the scsi/480 and the nvme/1600 disks.  So it will match the search criteria.
