### ISSUE TITLE
Data-model suggestion

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/quads#62]
Today's data-model:

```yaml
hosts:
  my.host0.com:
    cloud: cloud01
    interfaces: {}
    schedule:
      0:
        cloud: cloud06
        end: 2017-05-14 22:00
        start: 2017-04-16 22:00
```

The new data-model I am suggesting would be the following

```yaml
hosts:
  my.host0.com:
    cloud: cloud01
    interfaces: {}
    schedule:
      0:
        cloud: cloud06
        end:
          year: 2017
          month: 05
          day: 14
          time: 22:00
        start: 
          year: 2017
          month: 04
          day: 16
          time: 22:00
```
